steps:
- name: 'google/cloud-sdk:slim'
  entrypoint: 'gcloud'
  args: ['functions', 'deploy', 'sendScheduledNotificationsGen2', '--gen2', '--trigger-http', '--runtime=${_RUNTIME}', '--timeout=3600s', '--memory=2048MB', '--ingress-settings=internal-only', '--region=us-central1', '--env-vars-file=${_ENV_FILE}']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['functions', 'deploy', 'participantsEligibleForIncentive', '--trigger-http', '--runtime=${_RUNTIME}', '--source=${_SOURCE}', '--env-vars-file=${_ENV_FILE}']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['functions', 'add-iam-policy-binding', 'participantsEligibleForIncentive', '--member=allUsers', '--role=${_ROLE}']
substitutions:
  _SOURCE: https://source.developers.google.com/projects/nih-nci-dceg-connect-prod-6d04/repos/github_nci-c4cp_connectfaas
  _RUNTIME: nodejs20
  _ROLE: roles/cloudfunctions.invoker
  _ENV_FILE: config/prod/.env.yaml
