steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['functions', 'deploy', 'importNotificationsToBigquery', '--trigger-resource=${_RESOURCE}', '--trigger-event=${_EVENT}', '--runtime=${_RUNTIME}', '--timeout=480s', '--source=${_SOURCE}', '--env-vars-file=config/prod/.env.yaml']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['functions', 'deploy', 'exportNotificationsToBucket', '--trigger-topic=${_TOPIC}', '--runtime=${_RUNTIME}', '--timeout=480s', '--source=${_SOURCE}', '--env-vars-file=config/prod/.env.yaml']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['functions', 'deploy', 'webhook', '--trigger-http', '--runtime=${_RUNTIME}', '--timeout=240s', '--memory=1024MB',  '--source=${_SOURCE}', '--env-vars-file=config/prod/.env.yaml']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['functions', 'add-iam-policy-binding', 'webhook', '--member=allUsers', '--role=${_ROLE}'] 
substitutions:
  _SOURCE: https://source.developers.google.com/projects/nih-nci-dceg-connect-prod-6d04/repos/github_nci-c4cp_connectfaas
  _RUNTIME: nodejs20
  _ROLE: roles/cloudfunctions.invoker
  _RESOURCE: myconnect_firestore_backup_prod
  _EVENT: google.storage.object.finalize
  _TOPIC: Daily-Notifications-Backup