steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['functions', 'deploy', 'sendScheduledNotifications', '--trigger-topic=${_TOPIC}', '--runtime=${_RUNTIME}', '--timeout=540s', '--memory=2048MB', '--source=${_SOURCE}', '--env-vars-file=config/prod/.env.yaml']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['functions', 'deploy', 'participantsEligibleForIncentive', '--trigger-http', '--runtime=${_RUNTIME}', '--source=${_SOURCE}', '--env-vars-file=config/prod/.env.yaml']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['functions', 'add-iam-policy-binding', 'participantsEligibleForIncentive', '--member=allUsers', '--role=${_ROLE}']
substitutions:
  _SOURCE: https://source.developers.google.com/projects/nih-nci-dceg-connect-prod-6d04/repos/github_episphere_connectfaas
  _RUNTIME: nodejs20
  _ROLE: roles/cloudfunctions.invoker
  _TOPIC: connect-notifications
