steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['functions', 'deploy', 'participantDataCleanup', '--trigger-topic=${_TOPIC}', '--runtime=${_RUNTIME}', '--timeout=480s', '--source=${_SOURCE}', '--env-vars-file=config/prod/.env.yaml']
substitutions:
  _SOURCE: https://source.developers.google.com/projects/nih-nci-dceg-connect-prod-6d04/repos/github_episphere_connectfaas
  _RUNTIME: nodejs14
  _ROLE: roles/cloudfunctions.invoker
  _RESOURCE: myconnect_firestore_backup_prod
  _EVENT: google.storage.object.finalize
  _TOPIC: participant-data-cleanup