steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['functions', 'deploy', 'updateParticipantData', '--trigger-http', '--runtime=${_RUNTIME}', '--source=${_SOURCE}']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['functions', 'add-iam-policy-binding', 'updateParticipantData', '--member=allUsers', '--role=${_ROLE}']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['functions', 'deploy', 'dashboard', '--trigger-http', '--runtime=${_RUNTIME}', '--timeout=240s', '--memory=1024MB', '--source=${_SOURCE}']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['functions', 'add-iam-policy-binding', 'dashboard', '--member=allUsers', '--role=${_ROLE}']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['functions', 'deploy', 'importToBigQuery', '--trigger-resource=${_RESOURCE}', '--trigger-event=${_EVENT}', '--runtime=${_RUNTIME}', '--timeout=480s', '--source=${_SOURCE}']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['functions', 'deploy', 'scheduleFirestoreDataExport', '--trigger-topic=${_TOPIC}', '--runtime=${_RUNTIME}', '--timeout=480s', '--source=${_SOURCE}', '--set-env-vars .env.yaml']
substitutions:
  _SOURCE: https://source.developers.google.com/projects/nih-nci-dceg-connect-dev/repos/github_episphere_connectfaas
  _RUNTIME: nodejs12
  _ROLE: roles/cloudfunctions.invoker
  _RESOURCE: connect_firestore_dev_backup
  _EVENT: google.storage.object.finalize
  _TOPIC: schedule-firestore-backup
