steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['functions', 'deploy', 'identifyParticipant', '--trigger-http', '--runtime=nodejs10', '--source=https://source.developers.google.com/projects/nih-nci-dceg-episphere-dev/repos/github_episphere_connectfaas']
  dir: 'functions/autodeploy'
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['functions', 'deploy', 'generateToken', '--trigger-http', '--runtime=nodejs10', '--source=https://source.developers.google.com/projects/nih-nci-dceg-episphere-dev/repos/github_episphere_connectfaas']
  dir: 'functions/autodeploy'
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['functions', 'deploy', 'submitParticipantsData', '--trigger-http', '--runtime=nodejs10', '--timeout=120s', '--source=https://source.developers.google.com/projects/nih-nci-dceg-episphere-dev/repos/github_episphere_connectfaas']
  dir: 'functions/autodeploy'
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['functions', 'deploy', 'subscribeToNotification', '--trigger-http', '--runtime=nodejs10', '--source=https://source.developers.google.com/projects/nih-nci-dceg-episphere-dev/repos/github_episphere_connectfaas']
  dir: 'functions/autodeploy'
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['functions', 'deploy', 'retrieveNotifications', '--trigger-http', '--runtime=nodejs10', '--source=https://source.developers.google.com/projects/nih-nci-dceg-episphere-dev/repos/github_episphere_connectfaas']
  dir: 'functions/autodeploy'
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['functions', 'deploy', 'uploadHealthRecords', '--trigger-http', '--runtime=nodejs10', '--source=https://source.developers.google.com/projects/nih-nci-dceg-episphere-dev/repos/github_episphere_connectfaas']
  dir: 'functions/autodeploy'
  