steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['functions', 'deploy', 'identifyParticipant', '--trigger-http', '--runtime=nodejs12', '--timeout=120s', '--source=${_SOURCE}']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['functions', 'add-iam-policy-binding', 'identifyParticipant', '--member=allUsers', '--role=roles/cloudfunctions.invoker']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['functions', 'deploy', 'submitParticipantsData', '--trigger-http', '--runtime=nodejs12', '--timeout=120s', '--source=${_SOURCE}']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['functions', 'add-iam-policy-binding', 'submitParticipantsData', '--member=allUsers', '--role=roles/cloudfunctions.invoker']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['functions', 'deploy', 'biospecimen', '--trigger-http', '--runtime=nodejs12', '--source=${_SOURCE}']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['functions', 'add-iam-policy-binding', 'biospecimen', '--member=allUsers', '--role=roles/cloudfunctions.invoker']
substitutions:
  _SOURCE: https://source.developers.google.com/projects/nih-nci-dceg-connect-stg-5519/repos/github_episphere_connectfaas