steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['functions', 'deploy', 'updateParticipantData', '--trigger-http', '--runtime=nodejs12', '--source=https://source.developers.google.com/projects/nih-nci-dceg-connect-stg-5519/repos/github_episphere_connectfaas']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['functions', 'add-iam-policy-binding', 'updateParticipantData', '--member=allUsers', '--role=roles/cloudfunctions.invoker']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['functions', 'deploy', 'dashboard', '--trigger-http', '--runtime=nodejs12', '--timeout=240s', '--memory=1024MB', '--source=https://source.developers.google.com/projects/nih-nci-dceg-connect-stg-5519/repos/github_episphere_connectfaas']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['functions', 'add-iam-policy-binding', 'dashboard', '--member=allUsers', '--role=roles/cloudfunctions.invoker']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['functions', 'deploy', 'importToBigQuery', '--trigger-resource=connect_firestore_dev_backup', '--trigger-event=google.storage.object.finalize', '--runtime=nodejs12', '--timeout=480s', '--source=https://source.developers.google.com/projects/nih-nci-dceg-connect-stg-5519/repos/github_episphere_connectfaas']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['functions', 'deploy', 'scheduleFirestoreDataExport', '--trigger-topic=schedule-firestore-backup', '--runtime=nodejs12', '--timeout=480s', '--source=https://source.developers.google.com/projects/nih-nci-dceg-connect-stg-5519/repos/github_episphere_connectfaas']