steps:

- name: 'bash'
  args:
  - '-c'
  - |
    # Random sleep between 1 and 45 seconds
    SLEEP_TIME=$(( ( RANDOM % 45 ) + 1 ))
    echo "Staggering start by $SLEEP_TIME seconds..."
    sleep $SLEEP_TIME

- name: 'gcr.io/cloud-builders/gcloud'
  args: [
    'run',
    'deploy', 
    '${_SERVICE}',
    '--region=${_REGION}',
    '--source=${_SOURCE}',
    '--function=${_FUNCTION}',
    '--base-image=${_BASE_IMAGE}',
    '--memory=${_MEMORY}',
    '--timeout=${_TIMEOUT}',
    '--ingress=internal',
    '--env-vars-file=${_VARIABLES}'
  ]

substitutions:
  _BASE_IMAGE: us-central1-docker.pkg.dev/serverless-runtimes/google-22-full/runtimes/nodejs20
  _FUNCTION: generateDHQReports
  _MEMORY: 1024Mi
  _REGION: us-central1
  _SERVICE: generatedhqreports
  _SOURCE: .
  _TIMEOUT: 540s