const { defaultFlags, developmentTier, VALID_TIERS } = require("./shared");

const toFieldKey = (value) => String(value);

// Names of nested parent keys (participant doc). Used by the resolver.
// Builtins like "query" and "state" already match their doc key and don't need an entry here.
const NESTED_PARENT_CID_MAP = {
    physicalActivity: 686238347,
};

// V0 Data Destruction Stub Variables at the V1 pre-release commit, when Data Destruction auditing was introduced (May 2026 release).
// firebaseAuthenticationEmail: (V1 removed)
// dateRevokedHIPAA: (V1 added)
// Note on dhq3Username: it is not retained. It is a DHQ-side respondent
// ID that would re-identify the participant if linked back to DHQ records.
// The trade-off is that, by breaking the linkage, we can't audit that variable.
// V0 locked for versioning/auditing. Do not edit. To update the data destruction process for new requirements, create a new delta in DATA_DESTRUCTION_POLICY_DELTAS.
const V0_DATA_DESTRUCTION_STUB_VARS = {
    consentFirstName: 471168198,
    consentMiddleName: 436680969,
    consentLastName: 736251808,
    consentSuffixName: 480305327,
    userProfileNameFirstName: 399159511,
    userProfileNameMiddleName: 231676651,
    userProfileNameLastName: 996038075,
    userProfileNameSuffixName: 506826178,
    dateOfBirth: 371067537,
    birthMonth: 564964481,
    birthDay: 795827569,
    birthYear: 544150384,
    healthcareProvider: 827220437,
    informedConsentFlag: 919254129,
    informedConsentVersion: 454205108,
    informedConsentDateSigned: 454445267,
    verificationStatus: 821247024,
    verificationDate: 914594314,
    hipaaAuthorizationFlag: 558435199,
    hipaaAuthorizationVersion: 412000022,
    hipaaAuthorizationDateSigned: 262613359,
    userProfileSubmittedFlag: 699625233,
    hipaaRevocationFlag: 773707518,
    withdrawalFlag: 747006172,
    dateOfWithdrawal: 659990606,
    whoRequestedWithdrawal: 299274441,
    whoRequestedWithdrawalOther: 457532784,
    reasonsForWithdrawal: 919699172,
    tooBusy: 141450621,
    incentiveTooLow: 576083042,
    tooSick: 431428747,
    unreliableInternetDevice: 121430614,
    worriedAboutStudyResults: 523768810,
    worriedStudyWillFindSomethingBad: 639172801,
    privacyConcerns: 175732191,
    doNotTrustGov: 150818546,
    doNotTrustRsrchrs: 624030581,
    doNotWantInfoSharedWithRsrchrs: 285488731,
    worriedInfoNotSecure: 596510649,
    worriedInsWillGetData: 866089092,
    worriedAboutDataBeingGivenToMyEmployerPotentialEmployer: 990579614,
    worriedAboutDiscriminationFromData: 131458944,
    worriedOthersWillProfitFromMyData: 372303208,
    otherPrivacyConcerns: 777719027,
    unableToCompleteOnlineActivities: 620696506,
    concernedAboutInfoOnline: 637147033,
    technicalProblems: 440351122,
    doNotLikeThingsOnline: 352891568,
    covidConcerns: 958588520,
    partNowUnableToParticipate: 875010152,
    partIncarcerated: 404289911,
    reasonNotGiven: 538619788,
    otherReasonsSpecify: 715390138,
    otherReasons: 734828170,
    hipaaRevocationFormHasBeenSigned: 153713899,
    hipaaRevocationCategorical: 577794331,
    dateOfSignatureOnHIPAARevocationForm: 613641698,
    versionOfTheHIPAARevocationForm: 407743866,
    nameExtractedFromSignedHIPAARevocationFormFirstName: 765336427,
    nameExtractedFromSignedHIPAARevocationFormMiddleName: 826240317,
    nameExtractedFromSignedHIPAARevocationFormLastName: 479278368,
    nameExtractedFromSignedHIPAARevocationFormSuffix: 693626233,
    dataDestructionRequest: 831041022,
    dateOfDestructionRequest: 269050420,
    whoRequestedDataDestruction: 524352591,
    whoRequestedDataDestructionOther: 902332801,
    dataDestructionRequestFormHasBeenSigned: 359404406,
    dataDestructionCategoricalFlag: 883668444,
    dateOfSignatureOnDataDestructionRequestForm: 119449326,
    versionOfTheDataDestructionRequestForm: 304438543,
    nameExtractedFromSignedDataDestructionFormFirstName: 104278817,
    nameExtractedFromSignedDataDestructionFormMiddleName: 268665918,
    nameExtractedFromSignedDataDestructionFormLastName: 744604255,
    nameExtractedFromSignedDataDestructionFormSuffixName: 592227431,
    dataHasBeenDestroyedFlag: 861639549,
    dateTimeDataDestroyed: 652627623,
    participationStatus: 912301837,
    incentive: 130371375,
    incentiveEligible: 731498909,
    menstrualSurveyEligible: 289750687,
    dateIncentiveEligible: 787567527,
    norcIncentiveEligible: 222373868,
    incentiveIssued: 648936790,
    dateIncentiveIssued: 297462035,
    incentiveRefused: 648228701,
    dateIncentiveRefused: 438636757,
    norcCaseNumber: 320023644,
    bloodUrineMouthwashCombinedResearchSurveyFlag: 265193023,
    autogeneratedDateTimeWhenBloodUrineMouthwashResearchSurveyCompleted: 222161762,
    bloodUrineSurveyCompletionFlag: 253883960,
    autogeneratedDateTimeWhenBloodUrineSurveyCompleted: 764863765,
    mouthwashSurveyCompletionFlag: 547363263,
    autogeneratedDateTimeWhenMouthwashSurveyCompleted: 195145666,
    menstrualCycleSurveyCompletionFlag: 459098666,
    autogeneratedDateTimeWhenMenstrualCycleSurveyCompleted: 217640691,
    covid19SurveyCompletionFlag: 220186468,
    autogeneratedDateTimeWhenCOVID19SurveyCompleted: 784810139,
    surveyCompletionFlag: 320303124,
    autogeneratedDateTimeWhenPROMISSurveyCompleted: 843688458,
    baselineSurveyStatusModuleBackgroundAndOverallHealthFlag: 949302066,
    autogeneratedDateTimeStampForCompletionOfModuleBackgroundAndOverallHealth: 517311251,
    baselineSurveyStatusModuleMedications: 536735468,
    autogeneratedDateTimeStampForCompletionOfModuleMedications: 832139544,
    baselineSurveyStatusModuleSmoking: 976570371,
    autogeneratedDateTimeStampForCompletionOfModuleSmoking: 770257102,
    baselineSurveyStatusModuleWhereYouLiveAndWorkFlag: 663265240,
    autogeneratedDateTimeStampForCompletionOfModuleWhereYouLiveAndWork: 264644252,
    snsnSurveyFlag: 126331570,
    autogeneratedDateTimeWhenSSNSurveyCompleted: 315032037,
    allBiospecimenCollectionDetails: 173836415,
    baselineUrineCollected: 167958071,
    baselineBloodAndUrineIsRefused: 526455436,
    baselineMouthwashCollected: 684635302,
    baselineBloodSampleCollected: 878865966,
    allBaselineSamplesCollected: 254109640,
    bioSpmVisitV1r0: 331584571,
    allBaselineSurveysCompleted: 100767870,
    firebaseAuthenticationEmail: 421823980, // V1 removed. The auth email no longer survives destruction
    threeMonthQualityOfLifePromisSurveyCompletion: 320303124,
    autogeneratedDateTimeWhenPromisSurveyCompleted: 843688458,
    connectExperienceSurveyStatus: 956490759,
    autogeneratedDateimeStampForCompletionOf2024ConnectExperienceSurvey: 199471989,
    anyRefusalOrWithdrawal: 451953807,
    cancerScreeningHistorySurveyStatus: 176068627,
    cancerScreeningHistorySurveyCompletionTime: 389890053,
    dhq3SurveyStatus: 692560814,
    dhq3SurveyCompletionTime: 610227793,
    dhq3HEIReportStatusInternal: 542983589,
    dhq3HEIReportStatusExternal: 892697201,
    dhq3HEIReportFirstViewedISOTime: 600958089,
    numberOfAvailableReports: 794047378,
    physicalActivity: 686238347,
    flagForReportUnreadViewedDeclined: 446235715,
    dateRoiPaReportFirstViewed: 749055145,
    preference2026SurveyStatus: 278023676,
    preference2026SurveyCompletionTime: 543379310,
};

// Builtin top-level retained keys (literal strings, not CID-encoded on the doc).
const BUILTIN_RETAINED_TOP_LEVEL_NAMED_DATA_DESTRUCTION_VARS = {
    query: "query",
    pin: "pin",
    token: "token",
    state: "state",
    Connect_ID: "Connect_ID",
};

// Per-parent nested sub-field allowlists.
const V0_QUERY_RETAINED_SUBFIELDS = {
    firstName: "firstName",
    lastName: "lastName",
};
const V0_STATE_RETAINED_SUBFIELDS = {
    studyId: "studyId",
    uid: "uid",
};
const V0_PHYSICAL_ACTIVITY_RETAINED_SUBFIELDS = {
    flagForReportUnreadViewedDeclined: 446235715,
    dateRoiPaReportFirstViewed: 749055145,
};

const V0_DATA_DESTRUCTION_BASELINE = {
    version: "v0",
    retainedFieldsNamed: { ...V0_DATA_DESTRUCTION_STUB_VARS, ...BUILTIN_RETAINED_TOP_LEVEL_NAMED_DATA_DESTRUCTION_VARS },
    nestedRetainedFieldsNamed: {
        query:            { ...V0_QUERY_RETAINED_SUBFIELDS },
        state:            { ...V0_STATE_RETAINED_SUBFIELDS },
        physicalActivity: { ...V0_PHYSICAL_ACTIVITY_RETAINED_SUBFIELDS },
    },
    rationale:
        "Pre-versioning Data Destruction Policy baseline. Documented retroactively so audits of " +
        "participants destroyed before the May 2026 release are evaluated " +
        "against the policy that actually applied at their destruction time.",
};

// V1 delta: stub-variable changes relative to V0. Hardcoded per-tier deploy dates; null = not yet deployed to that tier.
// Add future deltas as V2, V3, etc. objects, then update the DATA_DESTRUCTION_POLICY_DELTAS list.
const V1_DATA_DESTRUCTION_STUB_VARS = {
    version: "v1",
    // ISO timestamps in UTC. EDT is (UTC-4) in May. Coincides with 10:00 ET prod release time.
    effectiveFrom: {
        DEV:   "2026-05-18T04:00:00.000Z", // 2026-05-18 00:00 ET
        STAGE: "2026-05-25T04:00:00.000Z", // 2026-05-25 00:00 ET
        PROD:  "2026-05-28T02:00:00.000Z", // 2026-05-27 22:00 ET
    },
    retainedFieldsNamed: {
        add:    { dateRevokedHIPAA: 664453818 },
        remove: { firebaseAuthenticationEmail: 421823980 },
    },
    nestedRetainedFieldsNamed: {
        // { parentName: { subName: cidOrLiteral } }
        add:    {},
        remove: {},
    },
    rationale:
        "Removed authenticationEmail (421823980) from retention. The auth " +
        "email no longer survives destruction. Added dateRevokedHIPAA " +
        "(664453818) so HIPAA revocation traceability is retained.",
};

const V2_DATA_DESTRUCTION_STUB_VARS = {
    version: "v2",
    effectiveFrom: {
        DEV:   "2026-07-20T04:00:00.000Z", // 2026-07-20 00:00 ET
        STAGE: "2026-07-27T04:00:00.000Z", // 2026-07-27 00:00 ET
        PROD:  "2026-08-01T02:00:00.000Z", // 2026-07-31 22:00 ET
    },
    retainedFieldsNamed: {
        add: {
            dietScreenerSurveyStatus: 301686481,
            dietScreenerSurveyCompletionTime: 676097165
        },
        remove: {},
    },
    nestedRetainedFieldsNamed: {
        add: {},
        remove: {},
    },
    rationale:
        "Retain dietScreenerSurveyStatus (301686481) and dietScreenerSurveyCompletionTime " +
        "(676097165) after participant data destruction.",
};

// Append future versions to this list. Each delta is applied to the running
// view in declared order if its tier-specific effectiveFrom is <= the
// participant's dateTimeDataDestroyed.
const DATA_DESTRUCTION_POLICY_DELTAS = [
    V1_DATA_DESTRUCTION_STUB_VARS,
    V2_DATA_DESTRUCTION_STUB_VARS
];

const hasOwn = (obj, key) => Object.prototype.hasOwnProperty.call(obj, key);

const isObject = (value) => (
    value !== null &&
    typeof value === "object" &&
    !Array.isArray(value)
);

const hasFieldPath = (obj, fieldPath) => {
    const parts = fieldPath.split(".");
    let curr = obj;
    for (const part of parts) {
        if (!isObject(curr) || !hasOwn(curr, part)) return false;
        curr = curr[part];
    }
    return curr !== undefined && curr !== null;
};

const applyDelta = (state, delta) => {
    const { retainedFieldsNamed, nestedRetainedFieldsNamed } = state;

    Object.keys(delta.retainedFieldsNamed?.remove || {}).forEach((name) => {
        delete retainedFieldsNamed[name];
    });
    Object.entries(delta.retainedFieldsNamed?.add || {}).forEach(([name, value]) => {
        retainedFieldsNamed[name] = value;
    });

    Object.entries(delta.nestedRetainedFieldsNamed?.remove || {}).forEach(([parentName, subMap]) => {
        if (!nestedRetainedFieldsNamed[parentName]) return;
        Object.keys(subMap).forEach((subName) => delete nestedRetainedFieldsNamed[parentName][subName]);
    });
    Object.entries(delta.nestedRetainedFieldsNamed?.add || {}).forEach(([parentName, subMap]) => {
        nestedRetainedFieldsNamed[parentName] = {
            ...(nestedRetainedFieldsNamed[parentName] || {}),
            ...subMap,
        };
    });
};

const cloneNamedNested = (nested) => Object.fromEntries(
    Object.entries(nested).map(([key, value]) => [key, { ...value }]),
);

const namedMapToCidArray = (named) => [
    ...new Set(Object.values(named).map(toFieldKey)),
];

const materializeNestedRetainedFields = (namedNested, parentCids = NESTED_PARENT_CID_MAP) => {
    const out = {};
    for (const [parentName, subMap] of Object.entries(namedNested)) {
        const docKey = String(parentCids[parentName] ?? parentName);
        out[docKey] = namedMapToCidArray(subMap);
    }
    return out;
};

/**
 * Resolve the policy that was effective for a participant's destruction.
 * Walks deltas in declared order and applies each where the tier-specific effectiveFrom is <= the destruction ISO.
 * Returns both the CID-form arrays that validate/buildDataDestructionUpdate consume and the name maps for audit output / ops handoff.
 *
 * `versions` and `baseline` are injectable for unit tests.
 */
const resolvePolicyForDestruction = (
    destructionIso,
    tier = developmentTier,
    versions = DATA_DESTRUCTION_POLICY_DELTAS,
    baseline = V0_DATA_DESTRUCTION_BASELINE,
) => {
    if (!VALID_TIERS.includes(tier)) {
        throw new Error(`Invalid tier "${tier}". Expected one of: ${VALID_TIERS.join(", ")}`);
    }

    const state = {
        retainedFieldsNamed: { ...baseline.retainedFieldsNamed },
        nestedRetainedFieldsNamed: cloneNamedNested(baseline.nestedRetainedFieldsNamed),
    };

    let resolvedVersion = baseline.version;
    let resolvedEffectiveFrom = null;
    const appliedDeltas = [];

    const destructionTime = destructionIso ? Date.parse(destructionIso) : NaN;
    if (Number.isFinite(destructionTime)) {
        for (const delta of versions) {
            const effectiveIso = delta.effectiveFrom?.[tier];
            if (!effectiveIso) continue;
            const effectiveTime = Date.parse(effectiveIso);
            if (!Number.isFinite(effectiveTime)) continue;
            if (effectiveTime > destructionTime) continue;

            applyDelta(state, delta);
            resolvedVersion = delta.version;
            resolvedEffectiveFrom = effectiveIso;
            appliedDeltas.push(delta.version);
        }
    }

    const retainedTopLevelFields = namedMapToCidArray(state.retainedFieldsNamed);
    const retainedSet = new Set(retainedTopLevelFields);
    const nestedRetainedFields = materializeNestedRetainedFields(state.nestedRetainedFieldsNamed);

    return {
        version: resolvedVersion,
        effectiveFrom: resolvedEffectiveFrom,
        appliedDeltas,
        retainedTopLevelFields,
        retainedFieldsNamed: state.retainedFieldsNamed,
        nestedRetainedFields,
        nestedRetainedFieldsNamed: state.nestedRetainedFieldsNamed,
        defaultFieldsRetainedIfPresent: Object.keys(defaultFlags)
            .map(toFieldKey)
            .filter((f) => retainedSet.has(f)),
    };
};

/**
 * Policy that applies to a destruction happening right now in `tier`. Used by production cleanup to know what to retain.
 */
const getCurrentPolicy = (tier = developmentTier) =>
    resolvePolicyForDestruction(new Date().toISOString(), tier);

/**
 * Ops-facing summary: returns the resolved policy as readable name→CID maps. Defaults to the policy that would apply to a destruction happening right now.
 */
const describeStubVariables = (policy = getCurrentPolicy()) => ({
    version: policy.version,
    effectiveFrom: policy.effectiveFrom,
    appliedDeltas: policy.appliedDeltas,
    retainedTopLevel: policy.retainedFieldsNamed,
    retainedNested: policy.nestedRetainedFieldsNamed,
});

/**
 * Build the Firestore update used by production cleanup to remove every field
 * not retained by the supplied policy view.
 */
const buildDataDestructionUpdate = (
    participantBefore,
    policy,
    options = {},
) => {
    if (!isObject(participantBefore)) {
        throw new Error("participantBefore must be an object");
    }
    if (!policy || !Array.isArray(policy.retainedTopLevelFields)) {
        throw new Error("policy with retainedTopLevelFields is required");
    }
    const deleteFieldValue = options.deleteFieldValue;
    if (typeof deleteFieldValue !== "function") {
        throw new Error("deleteFieldValue option is required");
    }

    const retainedFields = new Set(policy.retainedTopLevelFields.map(toFieldKey));
    const updateData = {};
    const deletedTopLevelFields = [];
    const deletedNestedFields = [];

    Object.keys(participantBefore).forEach((key) => {
        if (!retainedFields.has(key)) {
            updateData[key] = deleteFieldValue();
            deletedTopLevelFields.push(key);
            return;
        }

        const retainedNestedFields = policy.nestedRetainedFields[key];
        if (!retainedNestedFields || !isObject(participantBefore[key])) return;

        const retainedNestedSet = new Set(retainedNestedFields.map(toFieldKey));
        Object.keys(participantBefore[key]).forEach((subKey) => {
            if (!retainedNestedSet.has(subKey)) {
                const fieldPath = `${key}.${subKey}`;
                updateData[fieldPath] = deleteFieldValue();
                deletedNestedFields.push(fieldPath);
            }
        });
    });

    return {
        updateData,
        deletedTopLevelFields,
        deletedNestedFields,
    };
};

/**
 * Validate a destroyed stub against the supplied resolved policy.
 */
const validateDestroyedStub = (
    participantAfter,
    policy,
    options = {},
) => {
    if (!policy || !Array.isArray(policy.retainedTopLevelFields)) {
        throw new Error("policy with retainedTopLevelFields is required");
    }
    const participant = isObject(participantAfter) ? participantAfter : {};
    const retainedFields = new Set(policy.retainedTopLevelFields.map(toFieldKey));
    const unexpectedStubFields = [];
    const unexpectedNestedFields = [];
    const missingDefaultRetainedFields = [];

    Object.keys(participant).forEach((key) => {
        if (!retainedFields.has(key)) {
            unexpectedStubFields.push(key);
            return;
        }
        const retainedNestedFields = policy.nestedRetainedFields[key];
        if (!retainedNestedFields || !isObject(participant[key])) return;

        const retainedNestedSet = new Set(retainedNestedFields.map(toFieldKey));
        Object.keys(participant[key]).forEach((subKey) => {
            if (!retainedNestedSet.has(subKey)) {
                unexpectedNestedFields.push(`${key}.${subKey}`);
            }
        });
    });

    const participantBefore = options.participantBefore;
    if (isObject(participantBefore)) {
        policy.defaultFieldsRetainedIfPresent
            .filter((field) => hasOwn(participantBefore, field))
            .forEach((fieldPath) => {
                if (!hasFieldPath(participant, fieldPath)) {
                    missingDefaultRetainedFields.push(fieldPath);
                }
            });
    }

    let status = "pass";
    if (unexpectedStubFields.length > 0 || unexpectedNestedFields.length > 0) {
        status = "fail";
    } else if (missingDefaultRetainedFields.length > 0) {
        status = "warn";
    }

    return {
        policyVersion: policy.version,
        policyEffectiveFrom: policy.effectiveFrom || null,
        appliedDeltas: policy.appliedDeltas || [],
        status,
        unexpectedStubFields,
        unexpectedNestedFields,
        missingDefaultRetainedFields,
    };
};

module.exports = {
    V0_DATA_DESTRUCTION_BASELINE,
    V0_DATA_DESTRUCTION_STUB_VARS,
    V1_DATA_DESTRUCTION_STUB_VARS,
    V2_DATA_DESTRUCTION_STUB_VARS,
    DATA_DESTRUCTION_POLICY_DELTAS,
    NESTED_PARENT_CID_MAP,
    resolvePolicyForDestruction,
    getCurrentPolicy,
    describeStubVariables,
    applyDelta,
    buildDataDestructionUpdate,
    validateDestroyedStub,
};
