steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['functions', 'deploy', 'participantDataCleanup', '--trigger-topic=${_TOPIC}', '--runtime=${_RUNTIME}', '--timeout=480s', '--source=${_SOURCE}', '--env-vars-file=config/dev/.env.yaml']
substitutions:
  _SOURCE: https://source.developers.google.com/projects/nih-nci-dceg-connect-dev/repos/github_episphere_connectfaas/moveable-aliases/dev
  _RUNTIME: nodejs14
  _ROLE: roles/cloudfunctions.invoker
  _RESOURCE: connect_firestore_dev_backup
  _EVENT: google.storage.object.finalize
  _TOPIC: participant-data-cleanup