steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['functions', 'deploy', 'getBigQueryData', '--trigger-http', '--runtime=${_RUNTIME}', '--source=${_SOURCE}', '--env-vars-file=config/dev/.env.yaml']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['functions', 'add-iam-policy-binding', 'getBigQueryData', '--member=allUsers', '--role=${_ROLE}']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['functions', 'deploy', 'getParticipantToken', '--trigger-http', '--runtime=${_RUNTIME}', '--timeout=120s', '--source=${_SOURCE}', '--env-vars-file=config/dev/.env.yaml']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['functions', 'add-iam-policy-binding', 'getParticipantToken', '--member=allUsers', '--role=${_ROLE}']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['functions', 'deploy', 'participantDataCleanup', '--trigger-topic=${_TOPIC}', '--runtime=${_RUNTIME}', '--timeout=480s', '--source=${_SOURCE}', '--env-vars-file=config/dev/.env.yaml']
substitutions:
  _SOURCE: https://source.developers.google.com/projects/nih-nci-dceg-connect-dev/repos/github_nci-c4cp_connectfaas/moveable-aliases/dev
  _RUNTIME: nodejs20
  _ROLE: roles/cloudfunctions.invoker
  _TOPIC: participant-data-cleanup  