steps:

- name: 'gcr.io/cloud-builders/gcloud'
  args: [
    'functions', 
    'deploy', 
    '${_FUNCTION}', 
    '--trigger-http', 
    '--runtime=${_RUNTIME}', 
    '--timeout=${_TIMEOUT}', 
    '--source=${_SOURCE}', 
    '--env-vars-file=${_VARIABLES}'
  ]

- name: 'gcr.io/cloud-builders/gcloud'
  args: [
    'functions', 
    'add-iam-policy-binding', 
    '${_FUNCTION}', 
    '--member=${_MEMBER}', 
    '--role=${_ROLE}'
  ]

substitutions:
  _SOURCE: https://source.developers.google.com/projects/nih-nci-dceg-connect-dev/repos/github_nci-c4cp_connectfaas/moveable-aliases/dev
  _RUNTIME: nodejs20
  _ROLE: roles/cloudfunctions.invoker
  _TIMEOUT: 120s
  _VARIABLES: config/dev/.env.yaml
  _MEMBER: allUsers
  _FUNCTION: getParticipantsDemo