steps:

# updateParticipantData
- name: 'gcr.io/cloud-builders/gcloud'
  args: [
    'functions', 
    'deploy', 
    'updateParticipantData', 
    '--trigger-http', 
    '--runtime=${_RUNTIME}', 
    '--memory=${_MEMORY}',
    '--timeout=${_TIMEOUT}', 
    '--source=${_SOURCE}', 
    '--env-vars-file=${_VARIABLES}'
  ]

- name: 'gcr.io/cloud-builders/gcloud'
  args: [
    'functions', 
    'add-iam-policy-binding', 
    'updateParticipantData', 
    '--member=${_MEMBER}', 
    '--role=${_ROLE}'
  ]

# submitParticipantsData
- name: 'gcr.io/cloud-builders/gcloud'
  args: [
    'functions', 
    'deploy', 
    'submitParticipantsData', 
    '--trigger-http', 
    '--runtime=${_RUNTIME}', 
    '--memory=${_MEMORY}',
    '--timeout=${_TIMEOUT}', 
    '--source=${_SOURCE}', 
    '--env-vars-file=${_VARIABLES}'
  ]

- name: 'gcr.io/cloud-builders/gcloud'
  args: [
    'functions', 
    'add-iam-policy-binding', 
    'submitParticipantsData', 
    '--member=${_MEMBER}', 
    '--role=${_ROLE}'
  ]  

substitutions:
  _MEMBER: allUsers
  _MEMORY: 1024MB
  _ROLE: roles/cloudfunctions.invoker
  _RUNTIME: nodejs20
  _SOURCE: https://source.developers.google.com/projects/nih-nci-dceg-connect-dev/repos/github_nci-c4cp_connectfaas/moveable-aliases/dev
  _TIMEOUT: 240s
  _VARIABLES: config/dev/.env.yaml