steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['functions', 'deploy', 'importToBigQuery', '--trigger-resource=${_RESOURCE}', '--trigger-event=${_EVENT}', '--runtime=${_RUNTIME}', '--timeout=480s', '--source=${_SOURCE}', '--env-vars-file=config/stage/.env.yaml']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['functions', 'deploy', 'scheduleFirestoreDataExport', '--trigger-topic=${_TOPIC}', '--runtime=${_RUNTIME}', '--timeout=480s', '--source=${_SOURCE}', '--env-vars-file=config/stage/.env.yaml']
substitutions:
  _SOURCE: https://source.developers.google.com/projects/nih-nci-dceg-connect-stg-5519/repos/github_nci-c4cp_connectfaas/moveable-aliases/stage
  _RUNTIME: nodejs20
  _ROLE: roles/cloudfunctions.invoker
  _RESOURCE: myconnect_firestore_backup_stage
  _EVENT: google.storage.object.finalize
  _TOPIC: schedule-firestore-backup