const { setupTestSuite } = require('../shared/testHelpers');

let mocks;
let firestoreModule;
let fieldMapping;
let shared;

const makeDoc = (id, data = {}) => ({
    id,
    data: () => data,
    ref: { id, path: `collection/${id}` },
});

const makeSnapshot = (docs = []) => ({
    size: docs.length,
    empty: docs.length === 0,
    docs,
});

describe('resetParticipantHelper (deterministic)', () => {
    beforeAll(() => {
        const mockSystem = setupTestSuite({
            setupConsole: false,
            setupModuleMocks: true,
        });
        mocks = mockSystem.mocks;

        fieldMapping = require('../../utils/fieldToConceptIdMapping');
        shared = require('../../utils/shared');
        firestoreModule = require('../../utils/firestore');
    });

    it('should build reset payload and deletion map deterministically when saveToDb=false', async () => {
        const uid = 'uid-abc-123';
        const token = 'token-abc';
        const connectId = 1234567890;
        const participantDocId = 'participant-doc-1';
        const preservedVerificationTime = '2024-01-01T00:00:00.000Z';

        const participantData = {
            token,
            Connect_ID: connectId,
            query: { firstName: 'Test', lastName: 'User' },
            state: { uid, signedIn: true },
            [fieldMapping.verificationStatus]: fieldMapping.verified,
            [fieldMapping.autogeneratedVerificationStatusUpdatedTime]: preservedVerificationTime,
            [fieldMapping.address1]: '123 Fake Street',
            [fieldMapping.city]: 'Bethesda',
            [fieldMapping.state]: 'MD',
            [fieldMapping.zip]: '20892',
        };

        const moduleCollections = Object.values(shared.moduleConceptsToCollections);
        const sampleModuleCollection = moduleCollections[0];

        const queryResults = {
            participants: makeSnapshot([makeDoc(participantDocId, participantData)]),
            notifications: makeSnapshot([makeDoc('notif-1')]),
            biospecimen: makeSnapshot([makeDoc('bio-1', { token })]),
            cancerOccurrence: makeSnapshot([makeDoc('cancer-1')]),
            kitAssembly: makeSnapshot([makeDoc('kit-1')]),
            [sampleModuleCollection]: makeSnapshot([makeDoc('survey-1')]),
        };

        const emptySnapshot = makeSnapshot([]);
        const transactionSetSpy = vi.fn();
        const transactionDeleteSpy = vi.fn();

        mocks.firestore.collection.mockImplementation((collectionName) => ({
            where: vi.fn().mockImplementation((field, op, value) => ({
                __collectionName: collectionName,
                __field: field,
                __op: op,
                __value: value,
            })),
            doc: vi.fn().mockImplementation((docId) => ({
                id: docId,
                ref: { id: docId, path: `${collectionName}/${docId}` },
            })),
        }));

        mocks.firestore.runTransaction.mockImplementation(async (transactionCallback) => {
            const tx = {
                get: vi.fn().mockImplementation(async (query) => {
                    const collectionName = query && query.__collectionName;
                    if (!collectionName) return emptySnapshot;
                    return queryResults[collectionName] || emptySnapshot;
                }),
                set: transactionSetSpy,
                delete: transactionDeleteSpy,
            };
            return transactionCallback(tx);
        });

        const result = await firestoreModule.resetParticipantHelper(uid, false);

        expect(result).toBeTruthy();
        expect(result.data).toBeTruthy();
        expect(result.deleted).toBeTruthy();

        expect(result.data.state.uid).toBe(uid);
        expect(result.data.token).toBe(token);
        expect(result.data.Connect_ID).toBe(connectId);
        expect(result.data[fieldMapping.verificationStatus]).toBe(fieldMapping.verified);
        expect(result.data[fieldMapping.autogeneratedVerificationStatusUpdatedTime]).toBe(preservedVerificationTime);
        expect(result.data[fieldMapping.autogeneratedRecruitmentType]).toBe(fieldMapping.passive);
        expect(typeof result.data[fieldMapping.autogeneratedRecruitmentTypeTime]).toBe('string');
        expect(Object.prototype.hasOwnProperty.call(result.data, '983784715')).toBe(false);

        expect(result.deleted.notifications).toEqual(['notif-1']);
        expect(result.deleted.biospecimen).toEqual(['bio-1']);
        expect(result.deleted.cancerOccurrence).toEqual(['cancer-1']);
        expect(result.deleted.kitAssembly).toEqual(['kit-1']);
        expect(result.deleted[sampleModuleCollection]).toEqual(['survey-1']);

        expect(transactionSetSpy).not.toHaveBeenCalled();
        expect(transactionDeleteSpy).not.toHaveBeenCalled();
    });

    it('should return empty structures when participant is not found', async () => {
        mocks.firestore.collection.mockImplementation((collectionName) => ({
            where: vi.fn().mockImplementation((field, op, value) => ({
                __collectionName: collectionName,
                __field: field,
                __op: op,
                __value: value,
            })),
            doc: vi.fn(),
        }));

        mocks.firestore.runTransaction.mockImplementation(async (transactionCallback) => {
            const tx = {
                get: vi.fn().mockResolvedValue(makeSnapshot([])),
                set: vi.fn(),
                delete: vi.fn(),
            };
            return transactionCallback(tx);
        });

        const result = await firestoreModule.resetParticipantHelper('missing-uid', false);
        expect(result).toEqual({
            data: {},
            deleted: {},
        });
    });

    it('should persist reset and delete related docs in chunks when saveToDb=true', async () => {
        const uid = 'uid-save-path';
        const token = 'token-save-path';
        const connectId = 987654321;
        const participantDocId = 'participant-save-doc';
        const notificationIds = Array.from({ length: 61 }, (_, i) => `notif-${i + 1}`);

        const participantData = {
            token,
            Connect_ID: connectId,
            state: { uid },
            [fieldMapping.verificationStatus]: fieldMapping.verified,
        };

        const moduleCollections = Object.values(shared.moduleConceptsToCollections);
        const queryResults = {
            participants: makeSnapshot([makeDoc(participantDocId, participantData)]),
            notifications: makeSnapshot(notificationIds.map((id) => makeDoc(id))),
            biospecimen: makeSnapshot([]),
            cancerOccurrence: makeSnapshot([]),
            kitAssembly: makeSnapshot([]),
        };

        moduleCollections.forEach((collectionName) => {
            queryResults[collectionName] = makeSnapshot([]);
        });

        const whereCalls = [];
        const transactionSetSpy = vi.fn();
        const transactionDeleteSpy = vi.fn();

        mocks.firestore.collection.mockImplementation((collectionName) => ({
            where: vi.fn().mockImplementation((field, op, value) => {
                whereCalls.push({
                    collectionName,
                    field,
                    op,
                    value,
                });
                return {
                    __collectionName: collectionName,
                    __field: field,
                    __op: op,
                    __value: value,
                };
            }),
            doc: vi.fn().mockImplementation((docId) => ({
                id: docId,
                ref: { id: docId, path: `${collectionName}/${docId}` },
            })),
        }));

        mocks.firestore.runTransaction.mockImplementation(async (transactionCallback) => {
            const tx = {
                get: vi.fn().mockImplementation(async (query) => {
                    if (!query || !query.__collectionName) return makeSnapshot([]);

                    if (query.__op === 'in') {
                        const ids = Array.isArray(query.__value) ? query.__value : [];
                        return makeSnapshot(ids.map((id) => makeDoc(id)));
                    }

                    return queryResults[query.__collectionName] || makeSnapshot([]);
                }),
                set: transactionSetSpy,
                delete: transactionDeleteSpy,
            };
            return transactionCallback(tx);
        });

        const result = await firestoreModule.resetParticipantHelper(uid, true);

        expect(result.data.state.uid).toBe(uid);
        expect(result.deleted.notifications).toHaveLength(notificationIds.length);

        expect(transactionSetSpy).toHaveBeenCalledTimes(1);
        const [participantRef, participantPayload, setOptions] = transactionSetSpy.mock.calls[0];
        expect(participantRef.id).toBe(participantDocId);
        expect(participantPayload.state.uid).toBe(uid);
        expect(setOptions).toEqual({ merge: false });

        expect(transactionDeleteSpy).toHaveBeenCalledTimes(notificationIds.length);

        const notificationChunkCalls = whereCalls.filter(
            (call) => call.collectionName === 'notifications' && call.op === 'in',
        );
        expect(notificationChunkCalls).toHaveLength(3);
        expect(notificationChunkCalls.map((call) => call.value.length)).toEqual([30, 30, 1]);
    });

    it('should reject when a transaction query fails', async () => {
        const uid = 'uid-query-failure';
        const token = 'token-query-failure';

        const participantData = {
            token,
            Connect_ID: 123,
            state: { uid },
            [fieldMapping.verificationStatus]: fieldMapping.verified,
        };

        mocks.firestore.collection.mockImplementation((collectionName) => ({
            where: vi.fn().mockImplementation((field, op, value) => ({
                __collectionName: collectionName,
                __field: field,
                __op: op,
                __value: value,
            })),
            doc: vi.fn(),
        }));

        mocks.firestore.runTransaction.mockImplementation(async (transactionCallback) => {
            const tx = {
                get: vi.fn().mockImplementation(async (query) => {
                    if (query.__collectionName === 'participants') {
                        return makeSnapshot([makeDoc('participant-doc', participantData)]);
                    }
                    if (query.__collectionName === 'notifications') {
                        throw new Error('query-failed');
                    }
                    return makeSnapshot([]);
                }),
                set: vi.fn(),
                delete: vi.fn(),
            };
            return transactionCallback(tx);
        });

        await expect(firestoreModule.resetParticipantHelper(uid, false)).rejects.toThrow('query-failed');
    });
});
