const httpMocks = require('node-mocks-http');
const { setupTestSuite } = require('../shared/testHelpers');
const fieldMapping = require('../../utils/fieldToConceptIdMapping');

const siteCode = 1234567;
const authObj = {
    id: 'test-id',
    acronym: "ABC",
    isParent: false,
    coordinatingCenter: false,
    helpDesk: false,
    siteCodes: siteCode,
    userEmail: 'test@example.com',
};

let submitParticipantsData;
let updateParticipantData;
let updateRecruit;
let firestore;
let shared;
let validation;

beforeAll(() => {
    setupTestSuite({
        setupConsole: false,
        setupModuleMocks: true,
    });

    ({
        submitParticipantsData,
        updateParticipantData,
        updateRecruit,
    } = require('../../utils/sites'));
    firestore = require('../../utils/firestore');
    shared = require('../../utils/shared');
    validation = require('../../utils/validation');
});

const createRequest = (body) => httpMocks.createRequest({
    method: 'POST',
    headers: {
        'x-forwarded-for': 'unit-test',
    },
    connection: {},
    body,
});

const createResponse = () => httpMocks.createResponse();

const recruitTransitionCases = [
    {
        label: 'passive to active',
        existingRecruitType: fieldMapping.passiveRecruit,
        updateRecruitType: fieldMapping.passiveToActiveUpdate,
        expectedRecruitType: fieldMapping.activeRecruit,
    },
    {
        label: 'active to passive',
        existingRecruitType: fieldMapping.activeRecruit,
        updateRecruitType: fieldMapping.activeToPassiveUpdate,
        expectedRecruitType: fieldMapping.passiveRecruit,
    },
    {
        label: 'not active to passive',
        existingRecruitType: fieldMapping.notActiveRecruit,
        updateRecruitType: fieldMapping.notActiveToPassiveUpdate,
        expectedRecruitType: fieldMapping.passiveRecruit,
    },
];

describe('test changed functions', () => {
    describe('updateRecruit', () => {
        it.each(recruitTransitionCases)('applies the $label recruit transition', ({ existingRecruitType, updateRecruitType, expectedRecruitType }) => {
            const inputData = {
                [`state.${fieldMapping.updateRecruitType}`]: updateRecruitType,
            };
            const recordData = {
                [fieldMapping.autogeneratedRecruitmentType]: existingRecruitType,
            };

            updateRecruit(inputData, recordData);

            expect(inputData[fieldMapping.autogeneratedRecruitmentType]).toBe(expectedRecruitType);
        });

        it('does not update recruitment type when the transition is not eligible', () => {
            const inputData = {
                [`state.${fieldMapping.updateRecruitType}`]: fieldMapping.passiveToActiveUpdate,
            };
            const recordData = {
                [fieldMapping.autogeneratedRecruitmentType]: fieldMapping.activeRecruit,
            };

            updateRecruit(inputData, recordData);

            expect(inputData).toEqual({
                [`state.${fieldMapping.updateRecruitType}`]: fieldMapping.passiveToActiveUpdate,
            });
        });
    });

    describe('submitParticipantsData', () => {
        it.each(recruitTransitionCases)('writes the $label recruit transition', async ({ existingRecruitType, updateRecruitType, expectedRecruitType }) => {
            vi.spyOn(shared, 'APIAuthorization').mockResolvedValue({ siteCode });
            vi.spyOn(firestore, 'getParticipantData').mockResolvedValue({
                id: 'participant-doc',
                data: {
                    [fieldMapping.autogeneratedRecruitmentType]: existingRecruitType,
                    [fieldMapping.healthCareProvider]: siteCode,
                },
            });
            const updateParticipantDataByDocIdSpy = vi.spyOn(firestore, 'updateParticipantDataByDocId').mockResolvedValue();

            const req = createRequest({
                data: [{
                    token: 'participant-token',
                    [fieldMapping.updateRecruitType]: updateRecruitType,
                }],
            });
            const res = createResponse();

            await submitParticipantsData(req, res);

            expect(res.statusCode).toBe(200);
            expect(res._getJSONData()).toEqual({
                code: 200,
                results: [{
                    Success: {
                        Token: 'participant-token',
                        Errors: 'None',
                    },
                }],
            });
            expect(updateParticipantDataByDocIdSpy).toHaveBeenCalledWith('participant-doc', {
                [`state.${fieldMapping.updateRecruitType}`]: updateRecruitType,
                [fieldMapping.autogeneratedRecruitmentType]: expectedRecruitType,
            });
        });
    });

    describe('updateParticipantData', () => {
        it.each(recruitTransitionCases)('writes the $label recruit transition', async ({ existingRecruitType, updateRecruitType, expectedRecruitType }) => {
            vi.spyOn(firestore, 'getParticipantData').mockResolvedValue({
                id: 'participant-doc',
                data: {
                    [fieldMapping.autogeneratedRecruitmentType]: existingRecruitType,
                    [fieldMapping.healthCareProvider]: siteCode,
                },
            });
            const updateParticipantDataByDocIdSpy = vi.spyOn(firestore, 'updateParticipantDataByDocId').mockResolvedValue();
            const checkDerivedVariablesSpy = vi.spyOn(validation, 'checkDerivedVariables').mockResolvedValue();

            const req = createRequest({
                data: [{
                    token: 'participant-token',
                    state: {
                        [fieldMapping.updateRecruitType]: updateRecruitType,
                    },
                }],
            });
            const res = createResponse();

            await updateParticipantData(req, res, authObj);

            expect(res.statusCode).toBe(200);
            expect(updateParticipantDataByDocIdSpy).toHaveBeenCalledWith('participant-doc', {
                [`state.${fieldMapping.updateRecruitType}`]: updateRecruitType,
                [fieldMapping.autogeneratedRecruitmentType]: expectedRecruitType,
            });
            expect(checkDerivedVariablesSpy).toHaveBeenCalledWith('participant-token', siteCode);
        });

        it('records the participant update even when the site-notification email throws (best-effort policy)', async () => {
            vi.spyOn(firestore, 'getParticipantData').mockResolvedValue({
                id: 'participant-doc',
                data: {
                    'Connect_ID': '1234567890',
                    [fieldMapping.healthCareProvider]: siteCode,
                },
            });
            const updateParticipantDataByDocIdSpy = vi.spyOn(firestore, 'updateParticipantDataByDocId').mockResolvedValue();
            vi.spyOn(validation, 'checkDerivedVariables').mockResolvedValue();
            vi.spyOn(firestore, 'getSiteEmail').mockResolvedValue('site-and-cc-same@example.com');

            const siteNotifications = require('../../utils/siteNotifications');
            const sendGridErr = Object.assign(new Error('Bad Request'), { code: 400 });
            const handleSiteNotificationsSpy = vi.spyOn(siteNotifications, 'handleSiteNotifications')
                .mockRejectedValue(sendGridErr);
            const consoleErrorSpy = vi.spyOn(console, 'error').mockImplementation(() => {});

            // Payload that triggers the data-destruction site notification path
            // (all three: destroyData + withdrawConsent + revokeHIPAA = yes).
            const req = createRequest({
                data: [{
                    token: 'participant-token',
                    '831041022': 353358909,  // destroyData = yes
                    '747006172': 353358909,  // withdrawConsent = yes
                    '773707518': 353358909,  // revokeHIPAA = yes
                }],
            });
            const res = createResponse();

            await updateParticipantData(req, res, authObj);

            // The site notification was attempted (and threw under the hood).
            expect(handleSiteNotificationsSpy).toHaveBeenCalledTimes(1);

            // The participant write STILL happened — that's the whole point of best-effort.
            expect(updateParticipantDataByDocIdSpy).toHaveBeenCalledTimes(1);

            // The endpoint returns success (200), not 500/206 from a propagated email failure.
            expect(res.statusCode).toBe(200);

            // The failure was logged with the "non-fatal" structured marker for ops alerts.
            const nonFatalLog = consoleErrorSpy.mock.calls.find(([msg]) =>
                typeof msg === 'string' && msg.includes('Site notification failed (non-fatal)')
            );
            expect(nonFatalLog).toBeDefined();
            // Structured context should carry the concept + the SendGrid error code/message.
            const logContext = nonFatalLog[1];
            expect(logContext).toMatchObject({
                concept: '831041022',
                code: 400,
                error: 'Bad Request',
            });

            consoleErrorSpy.mockRestore();
        });

        it('adds a reinvitation timestamp for eligible active recruits', async () => {
            vi.spyOn(firestore, 'getParticipantData').mockResolvedValue({
                id: 'participant-doc',
                data: {
                    [fieldMapping.autogeneratedRecruitmentType]: fieldMapping.activeRecruit,
                    [fieldMapping.healthCareProvider]: siteCode,
                },
            });
            const updateParticipantDataByDocIdSpy = vi.spyOn(firestore, 'updateParticipantDataByDocId').mockResolvedValue();
            vi.spyOn(validation, 'checkDerivedVariables').mockResolvedValue();

            const req = createRequest({
                data: [{
                    token: 'participant-token',
                    [fieldMapping.reinvitationCampaignType]: 123456789,
                }],
            });
            const res = createResponse();

            await updateParticipantData(req, res, authObj);

            expect(res.statusCode).toBe(200);
            expect(updateParticipantDataByDocIdSpy).toHaveBeenCalledWith('participant-doc', {
                [fieldMapping.reinvitationCampaignType]: 123456789,
                [fieldMapping.reinvitationTimestamp]: expect.any(String),
            });

            const updates = updateParticipantDataByDocIdSpy.mock.calls[0][1];
            expect(Number.isNaN(Date.parse(updates[fieldMapping.reinvitationTimestamp]))).toBe(false);
        });
    });
});
