const httpMocks = require('node-mocks-http');
const { setupTestSuite } = require('../shared/testHelpers');
const fieldMapping = require('../../utils/fieldToConceptIdMapping');

const siteCode = 1234567;
const authObj = {
    id: 'test-id',
    acronym: "ABC",
    isParent: false,
    coordinatingCenter: false,
    helpDesk: false,
    siteCodes: siteCode,
    userEmail: 'test@example.com',
};

let submitParticipantsData;
let updateParticipantData;
let updateRecruit;
let geocodedAddresses;
let firestore;
let shared;
let validation;

beforeAll(() => {
    setupTestSuite({
        setupConsole: false,
        setupModuleMocks: true,
    });

    ({
        submitParticipantsData,
        updateParticipantData,
        updateRecruit,
        geocodedAddresses,
    } = require('../../utils/sites'));
    firestore = require('../../utils/firestore');
    shared = require('../../utils/shared');
    validation = require('../../utils/validation');
});

const createRequest = (body) => httpMocks.createRequest({
    method: 'POST',
    headers: {
        'x-forwarded-for': 'unit-test',
    },
    connection: {},
    body,
});

const createResponse = () => httpMocks.createResponse();

const recruitTransitionCases = [
    {
        label: 'passive to active',
        existingRecruitType: fieldMapping.passiveRecruit,
        updateRecruitType: fieldMapping.passiveToActiveUpdate,
        expectedRecruitType: fieldMapping.activeRecruit,
    },
    {
        label: 'active to passive',
        existingRecruitType: fieldMapping.activeRecruit,
        updateRecruitType: fieldMapping.activeToPassiveUpdate,
        expectedRecruitType: fieldMapping.passiveRecruit,
    },
    {
        label: 'not active to passive',
        existingRecruitType: fieldMapping.notActiveRecruit,
        updateRecruitType: fieldMapping.notActiveToPassiveUpdate,
        expectedRecruitType: fieldMapping.passiveRecruit,
    },
];

describe('test changed functions', () => {
    describe('updateRecruit', () => {
        it.each(recruitTransitionCases)('applies the $label recruit transition', ({ existingRecruitType, updateRecruitType, expectedRecruitType }) => {
            const inputData = {
                [`state.${fieldMapping.updateRecruitType}`]: updateRecruitType,
            };
            const recordData = {
                [fieldMapping.autogeneratedRecruitmentType]: existingRecruitType,
            };

            updateRecruit(inputData, recordData);

            expect(inputData[fieldMapping.autogeneratedRecruitmentType]).toBe(expectedRecruitType);
        });

        it('does not update recruitment type when the transition is not eligible', () => {
            const inputData = {
                [`state.${fieldMapping.updateRecruitType}`]: fieldMapping.passiveToActiveUpdate,
            };
            const recordData = {
                [fieldMapping.autogeneratedRecruitmentType]: fieldMapping.activeRecruit,
            };

            updateRecruit(inputData, recordData);

            expect(inputData).toEqual({
                [`state.${fieldMapping.updateRecruitType}`]: fieldMapping.passiveToActiveUpdate,
            });
        });
    });

    describe('submitParticipantsData', () => {
        it.each(recruitTransitionCases)('writes the $label recruit transition', async ({ existingRecruitType, updateRecruitType, expectedRecruitType }) => {
            vi.spyOn(shared, 'APIAuthorization').mockResolvedValue({ siteCode });
            vi.spyOn(firestore, 'getParticipantData').mockResolvedValue({
                id: 'participant-doc',
                data: {
                    [fieldMapping.autogeneratedRecruitmentType]: existingRecruitType,
                    [fieldMapping.healthCareProvider]: siteCode,
                },
            });
            const updateParticipantDataByDocIdSpy = vi.spyOn(firestore, 'updateParticipantDataByDocId').mockResolvedValue();

            const req = createRequest({
                data: [{
                    token: 'participant-token',
                    [fieldMapping.updateRecruitType]: updateRecruitType,
                }],
            });
            const res = createResponse();

            await submitParticipantsData(req, res);

            expect(res.statusCode).toBe(200);
            expect(res._getJSONData()).toEqual({
                code: 200,
                results: [{
                    Success: {
                        Token: 'participant-token',
                        Errors: 'None',
                    },
                }],
            });
            expect(updateParticipantDataByDocIdSpy).toHaveBeenCalledWith('participant-doc', {
                [`state.${fieldMapping.updateRecruitType}`]: updateRecruitType,
                [fieldMapping.autogeneratedRecruitmentType]: expectedRecruitType,
            });
        });
    });

    describe('updateParticipantData', () => {
        it.each(recruitTransitionCases)('writes the $label recruit transition', async ({ existingRecruitType, updateRecruitType, expectedRecruitType }) => {
            vi.spyOn(firestore, 'getParticipantData').mockResolvedValue({
                id: 'participant-doc',
                data: {
                    [fieldMapping.autogeneratedRecruitmentType]: existingRecruitType,
                    [fieldMapping.healthCareProvider]: siteCode,
                },
            });
            const updateParticipantDataByDocIdSpy = vi.spyOn(firestore, 'updateParticipantDataByDocId').mockResolvedValue();
            const checkDerivedVariablesSpy = vi.spyOn(validation, 'checkDerivedVariables').mockResolvedValue();

            const req = createRequest({
                data: [{
                    token: 'participant-token',
                    state: {
                        [fieldMapping.updateRecruitType]: updateRecruitType,
                    },
                }],
            });
            const res = createResponse();

            await updateParticipantData(req, res, authObj);

            expect(res.statusCode).toBe(200);
            expect(updateParticipantDataByDocIdSpy).toHaveBeenCalledWith('participant-doc', {
                [`state.${fieldMapping.updateRecruitType}`]: updateRecruitType,
                [fieldMapping.autogeneratedRecruitmentType]: expectedRecruitType,
            });
            expect(checkDerivedVariablesSpy).toHaveBeenCalledWith('participant-token', siteCode);
        });

        it('records the participant update even when the site-notification email throws (best-effort policy)', async () => {
            vi.spyOn(firestore, 'getParticipantData').mockResolvedValue({
                id: 'participant-doc',
                data: {
                    'Connect_ID': '1234567890',
                    [fieldMapping.healthCareProvider]: siteCode,
                },
            });
            const updateParticipantDataByDocIdSpy = vi.spyOn(firestore, 'updateParticipantDataByDocId').mockResolvedValue();
            vi.spyOn(validation, 'checkDerivedVariables').mockResolvedValue();
            vi.spyOn(firestore, 'getSiteEmail').mockResolvedValue('site-and-cc-same@example.com');

            const siteNotifications = require('../../utils/siteNotifications');
            const sendGridErr = Object.assign(new Error('Bad Request'), { code: 400 });
            const handleSiteNotificationsSpy = vi.spyOn(siteNotifications, 'handleSiteNotifications')
                .mockRejectedValue(sendGridErr);
            const consoleErrorSpy = vi.spyOn(console, 'error').mockImplementation(() => {});

            // Payload that triggers the data-destruction site notification path
            // (all three: destroyData + withdrawConsent + revokeHIPAA = yes).
            const req = createRequest({
                data: [{
                    token: 'participant-token',
                    '831041022': 353358909,  // destroyData = yes
                    '747006172': 353358909,  // withdrawConsent = yes
                    '773707518': 353358909,  // revokeHIPAA = yes
                }],
            });
            const res = createResponse();

            await updateParticipantData(req, res, authObj);

            // The site notification was attempted (and threw under the hood).
            expect(handleSiteNotificationsSpy).toHaveBeenCalledTimes(1);

            // The participant write STILL happened — that's the whole point of best-effort.
            expect(updateParticipantDataByDocIdSpy).toHaveBeenCalledTimes(1);

            // The endpoint returns success (200), not 500/206 from a propagated email failure.
            expect(res.statusCode).toBe(200);

            // The failure was logged with the "non-fatal" structured marker for ops alerts.
            const nonFatalLog = consoleErrorSpy.mock.calls.find(([msg]) =>
                typeof msg === 'string' && msg.includes('Site notification failed (non-fatal)')
            );
            expect(nonFatalLog).toBeDefined();
            // Structured context should carry the concept + the SendGrid error code/message.
            const logContext = nonFatalLog[1];
            expect(logContext).toMatchObject({
                concept: '831041022',
                code: 400,
                error: 'Bad Request',
            });

            consoleErrorSpy.mockRestore();
        });

        it('adds a reinvitation timestamp for eligible active recruits', async () => {
            vi.spyOn(firestore, 'getParticipantData').mockResolvedValue({
                id: 'participant-doc',
                data: {
                    [fieldMapping.autogeneratedRecruitmentType]: fieldMapping.activeRecruit,
                    [fieldMapping.healthCareProvider]: siteCode,
                },
            });
            const updateParticipantDataByDocIdSpy = vi.spyOn(firestore, 'updateParticipantDataByDocId').mockResolvedValue();
            vi.spyOn(validation, 'checkDerivedVariables').mockResolvedValue();

            const req = createRequest({
                data: [{
                    token: 'participant-token',
                    [fieldMapping.reinvitationCampaignType]: 123456789,
                }],
            });
            const res = createResponse();

            await updateParticipantData(req, res, authObj);

            expect(res.statusCode).toBe(200);
            expect(updateParticipantDataByDocIdSpy).toHaveBeenCalledWith('participant-doc', {
                [fieldMapping.reinvitationCampaignType]: 123456789,
                [fieldMapping.reinvitationTimestamp]: expect.any(String),
            });

            const updates = updateParticipantDataByDocIdSpy.mock.calls[0][1];
            expect(Number.isNaN(Date.parse(updates[fieldMapping.reinvitationTimestamp]))).toBe(false);
        });
    });
});

describe('geocodedAddresses', () => {
    const norcAuth = { acronym: 'NORC', siteCode: 123456 };

    // Valid values for the two required fields (758212868 and 625954624).
    const requiredFields = { '758212868': 12345, '625954624': 'geocode-id-abc123' };

    const createGeoRequest = (body) => httpMocks.createRequest({
        method: 'POST',
        headers: {
            'x-forwarded-for': 'unit-test',
            authorization: 'Bearer fake-token',
        },
        connection: {},
        body,
    });

    const createResponse = () => httpMocks.createResponse();

    // Build the Map that getParticipantsDataByConnectIds resolves to, keyed by Connect_ID.
    const participantMapOf = (...records) => {
        const map = new Map();
        for (const record of records) map.set(record.data.Connect_ID, record);
        return map;
    };

    it('returns 200 and stores valid rows', async () => {
        vi.spyOn(shared, 'APIAuthorization').mockResolvedValue(norcAuth);
        vi.spyOn(firestore, 'getParticipantsDataByConnectIds').mockResolvedValue(participantMapOf({
            id: 'participant-doc',
            data: { Connect_ID: 1234567890 },
        }));
        const writeSpy = vi.spyOn(firestore, 'writeGeocodedAddresses').mockResolvedValue();

        const req = createGeoRequest({
            data: [{
                Connect_ID: 1234567890,
                ...requiredFields,
                '826796611': '123 Main St',
                '202200799': 'IL',
            }],
        });
        const res = createResponse();

        await geocodedAddresses(req, res);

        expect(res.statusCode).toBe(200);
        expect(res._getJSONData().code).toBe(200);
        expect(res._getJSONData().results[0]).toHaveProperty('Success');
        expect(writeSpy).toHaveBeenCalledTimes(1);
        expect(writeSpy).toHaveBeenCalledWith([{
            connectId: 1234567890,
            fields: {
                ...requiredFields,
                '826796611': '123 Main St',
                '202200799': 'IL',
            },
        }]);
    });

    it('returns 206 with mixed valid and invalid rows (partial acceptance)', async () => {
        vi.spyOn(shared, 'APIAuthorization').mockResolvedValue(norcAuth);
        // Only 1111111111 exists; 9999999999 is absent from the map.
        vi.spyOn(firestore, 'getParticipantsDataByConnectIds').mockResolvedValue(participantMapOf({
            id: 'doc-1',
            data: { Connect_ID: 1111111111 },
        }));
        const writeSpy = vi.spyOn(firestore, 'writeGeocodedAddresses').mockResolvedValue();

        const req = createGeoRequest({
            data: [
                { Connect_ID: 1111111111, ...requiredFields, '202200799': 'NY' },
                { Connect_ID: 9999999999 },
            ],
        });
        const res = createResponse();

        await geocodedAddresses(req, res);

        expect(res.statusCode).toBe(206);
        const results = res._getJSONData().results;
        expect(results[0]).toHaveProperty('Success');
        expect(results[1]).toHaveProperty('Invalid Request');
        expect(writeSpy).toHaveBeenCalledTimes(1);
        expect(writeSpy.mock.calls[0][0]).toHaveLength(1);
    });

    it('rejects rows with missing Connect_ID', async () => {
        vi.spyOn(shared, 'APIAuthorization').mockResolvedValue(norcAuth);
        vi.spyOn(firestore, 'getParticipantsDataByConnectIds').mockResolvedValue(participantMapOf());

        const req = createGeoRequest({
            data: [{ '202200799': 'CA' }],
        });
        const res = createResponse();

        await geocodedAddresses(req, res);

        expect(res.statusCode).toBe(206);
        const result = res._getJSONData().results[0];
        expect(result['Invalid Request'].Connect_ID).toBe('UNDEFINED');
    });

    it('rejects rows for destroyed participants', async () => {
        vi.spyOn(shared, 'APIAuthorization').mockResolvedValue(norcAuth);
        vi.spyOn(firestore, 'getParticipantsDataByConnectIds').mockResolvedValue(participantMapOf({
            id: 'doc-destroyed',
            data: {
                Connect_ID: 5555555555,
                [fieldMapping.participantMap.dataHasBeenDestroyed]: fieldMapping.yes,
            },
        }));

        const req = createGeoRequest({
            data: [{ Connect_ID: 5555555555, '202200799': 'TX' }],
        });
        const res = createResponse();

        await geocodedAddresses(req, res);

        expect(res.statusCode).toBe(206);
        expect(res._getJSONData().results[0]['Invalid Request'].Errors).toBe('Data Destroyed');
    });

    it('rejects rows with validation errors (wrong type)', async () => {
        vi.spyOn(shared, 'APIAuthorization').mockResolvedValue(norcAuth);
        vi.spyOn(firestore, 'getParticipantsDataByConnectIds').mockResolvedValue(participantMapOf({
            id: 'doc-1',
            data: { Connect_ID: 1111111111 },
        }));

        const req = createGeoRequest({
            data: [{
                Connect_ID: 1111111111,
                ...requiredFields,
                '202200799': 12345,
            }],
        });
        const res = createResponse();

        await geocodedAddresses(req, res);

        expect(res.statusCode).toBe(206);
        const errors = res._getJSONData().results[0]['Invalid Request'].Errors;
        expect(errors[0]).toContain('must be a string');
    });

    it('rejects rows with validation errors (exceeds maxLength)', async () => {
        vi.spyOn(shared, 'APIAuthorization').mockResolvedValue(norcAuth);
        vi.spyOn(firestore, 'getParticipantsDataByConnectIds').mockResolvedValue(participantMapOf({
            id: 'doc-1',
            data: { Connect_ID: 1111111111 },
        }));

        const req = createGeoRequest({
            data: [{
                Connect_ID: 1111111111,
                ...requiredFields,
                '202200799': 'ABC',
            }],
        });
        const res = createResponse();

        await geocodedAddresses(req, res);

        expect(res.statusCode).toBe(206);
        const errors = res._getJSONData().results[0]['Invalid Request'].Errors;
        expect(errors[0]).toContain('less than 2 characters');
    });

    it('rejects rows with number fields exceeding maxLength', async () => {
        vi.spyOn(shared, 'APIAuthorization').mockResolvedValue(norcAuth);
        vi.spyOn(firestore, 'getParticipantsDataByConnectIds').mockResolvedValue(participantMapOf({
            id: 'doc-1',
            data: { Connect_ID: 1111111111 },
        }));

        const req = createGeoRequest({
            data: [{
                Connect_ID: 1111111111,
                '758212868': 1234567, // rule: number, maxLength 6 -> 7 digits is too long
                '625954624': 'geocode-id-abc123',
            }],
        });
        const res = createResponse();

        await geocodedAddresses(req, res);

        expect(res.statusCode).toBe(206);
        const errors = res._getJSONData().results[0]['Invalid Request'].Errors;
        expect(errors[0]).toContain('less than 6 digits');
    });

    it('rejects rows with unknown concept IDs', async () => {
        vi.spyOn(shared, 'APIAuthorization').mockResolvedValue(norcAuth);
        vi.spyOn(firestore, 'getParticipantsDataByConnectIds').mockResolvedValue(participantMapOf({
            id: 'doc-1',
            data: { Connect_ID: 1111111111 },
        }));

        const req = createGeoRequest({
            data: [{
                Connect_ID: 1111111111,
                ...requiredFields,
                '999999999': 'unknown field',
            }],
        });
        const res = createResponse();

        await geocodedAddresses(req, res);

        expect(res.statusCode).toBe(206);
        const errors = res._getJSONData().results[0]['Invalid Request'].Errors;
        expect(errors[0]).toContain('No validation rule exists');
    });

    it('skips blank fields without error and stores non-blank fields', async () => {
        vi.spyOn(shared, 'APIAuthorization').mockResolvedValue(norcAuth);
        vi.spyOn(firestore, 'getParticipantsDataByConnectIds').mockResolvedValue(participantMapOf({
            id: 'doc-1',
            data: { Connect_ID: 1111111111 },
        }));
        const writeSpy = vi.spyOn(firestore, 'writeGeocodedAddresses').mockResolvedValue();

        const req = createGeoRequest({
            data: [{
                Connect_ID: 1111111111,
                ...requiredFields,
                '826796611': '456 Oak Ave',
                '202200799': '',
                '565540989': null,
            }],
        });
        const res = createResponse();

        await geocodedAddresses(req, res);

        expect(res.statusCode).toBe(200);
        expect(writeSpy).toHaveBeenCalledWith([{
            connectId: 1111111111,
            fields: { ...requiredFields, '826796611': '456 Oak Ave' },
        }]);
    });

    it('returns 500 if Firestore write fails', async () => {
        vi.spyOn(shared, 'APIAuthorization').mockResolvedValue(norcAuth);
        vi.spyOn(firestore, 'getParticipantsDataByConnectIds').mockResolvedValue(participantMapOf({
            id: 'doc-1',
            data: { Connect_ID: 1111111111 },
        }));
        vi.spyOn(firestore, 'writeGeocodedAddresses').mockRejectedValue(new Error('Firestore unavailable'));

        const req = createGeoRequest({
            data: [{ Connect_ID: 1111111111, ...requiredFields, '202200799': 'CA' }],
        });
        const res = createResponse();

        await geocodedAddresses(req, res);

        expect(res.statusCode).toBe(500);
    });

    it('rejects rows where all fields are blank', async () => {
        vi.spyOn(shared, 'APIAuthorization').mockResolvedValue(norcAuth);
        vi.spyOn(firestore, 'getParticipantsDataByConnectIds').mockResolvedValue(participantMapOf({
            id: 'doc-1',
            data: { Connect_ID: 1111111111 },
        }));

        const req = createGeoRequest({
            data: [{
                Connect_ID: 1111111111,
                '826796611': '',
                '202200799': null,
            }],
        });
        const res = createResponse();

        await geocodedAddresses(req, res);

        expect(res.statusCode).toBe(206);
        expect(res._getJSONData().results[0]['Invalid Request'].Errors).toBe('No non-blank fields provided.');
    });

    it('rejects rows missing required fields', async () => {
        vi.spyOn(shared, 'APIAuthorization').mockResolvedValue(norcAuth);
        vi.spyOn(firestore, 'getParticipantsDataByConnectIds').mockResolvedValue(participantMapOf({
            id: 'doc-1',
            data: { Connect_ID: 1111111111 },
        }));

        const req = createGeoRequest({
            data: [{
                Connect_ID: 1111111111,
                '202200799': 'CA',
            }],
        });
        const res = createResponse();

        await geocodedAddresses(req, res);

        expect(res.statusCode).toBe(206);
        const error = res._getJSONData().results[0]['Invalid Request'].Errors;
        expect(error).toContain('Missing required field(s)');
        expect(error).toContain('758212868');
        expect(error).toContain('625954624');
    });

    it('returns 500 if the participant batch lookup fails', async () => {
        vi.spyOn(shared, 'APIAuthorization').mockResolvedValue(norcAuth);
        vi.spyOn(firestore, 'getParticipantsDataByConnectIds').mockRejectedValue(
            new Error('Firestore unavailable')
        );

        const req = createGeoRequest({
            data: [{ Connect_ID: 1111111111, '202200799': 'CA' }],
        });
        const res = createResponse();

        await geocodedAddresses(req, res);

        expect(res.statusCode).toBe(500);
    });

    it('normalizes Connect_ID to number for consistent hashing', async () => {
        vi.spyOn(shared, 'APIAuthorization').mockResolvedValue(norcAuth);
        vi.spyOn(firestore, 'getParticipantsDataByConnectIds').mockResolvedValue(participantMapOf({
            id: 'doc-1',
            data: { Connect_ID: 1111111111 },
        }));
        const writeSpy = vi.spyOn(firestore, 'writeGeocodedAddresses').mockResolvedValue();

        const req = createGeoRequest({
            data: [{ Connect_ID: '1111111111', ...requiredFields, '202200799': 'CA' }],
        });
        const res = createResponse();

        await geocodedAddresses(req, res);

        expect(res.statusCode).toBe(200);
        expect(writeSpy.mock.calls[0][0][0].connectId).toBe(1111111111);
        expect(typeof writeSpy.mock.calls[0][0][0].connectId).toBe('number');
    });
});
